#!/bin/sh

st & # simple X terminal

gnome-settings-daemon & # system settings
nm-applet & # network manager
bluetooth-applet &
#/usr/lib/gnome-disk-utility/gdu-notification-daemon &
#/usr/bin/gnome-keyring-daemon --daemonize --login &
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 & # makes empathy dialogue go away :P
#/usr/lib/gnome-settings-daemon/gnome-fallback-mount-helper & # auto mounter
#zeitgeist-datahub &
#telepathy-indicator &
#/usr/bin/python /usr/share/system-config-printer/applet.py &
#/usr/lib/evolution/3.2/evolution-alarm-notify &
#/usr/bin/python /usr/bin/gwibber-service &
#update-notifier &
#/usr/lib/deja-dup/deja-dup/deja-dup-monitor &
#/usr/bin/python /usr/lib/ubuntuone-client/ubuntuone-syncdaemon &
xsetroot -solid black &

while true; do
	xsetroot -name "$(pactl list sinks | grep Volume | grep -v Base | sed -r 's/\s*Volume: 0:\s*([0-9]+%).*$/vol: \1/g') $(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | sed -r 's/^\s*percentage:\s*([0-9]*)\.?.*$/bat: \1%/') $(date --rfc-3339=seconds)"
	sleep 1
done &
 
dwm
